### ISSUE TITLE
Test $ClientApp again

### ISSUE THREAD

**Issue by jlnr** [jlnr/JLNRBarController#13]
After most of the changes here have been merged, I should test my client's app again.

Note: I think the last version of the app changed with a bugfix which I never pushed to this repository. Screenshot of the Git diff:

![bildschirmfoto 2015-09-24 um 22 44 18](https://cloud.githubusercontent.com/assets/70772/10102877/4312087a-63a1-11e5-97ec-e2b586004464.png)

**Comment by sebastianludwig** [comment]
I think I found this one. I'll report...

**Comment by sebastianludwig** [comment]
Yes, I had to change the same line. See 95a8c48

**Comment by jlnr** [comment]
@sebastianludwig - then the delegate method should be called `willSelectItemAt...:`

**Comment by sebastianludwig** [comment]
True dat
