### ISSUE TITLE
support badges

### ISSUE THREAD

**Issue by sebastianludwig** [jlnr/JLNRBarController#4]
It'd be nice if the `UITabBarItem.badgeValue` would be displayed in a round badge as it is in `UITabBarController`.

- [x] match layout to `UITabBarBadge`

**Comment by sebastianludwig** [comment]
The initial plan to use KVO was good, however not prepared for reality

> Note: Although the classes of the UIKit framework generally do not support KVO, you can still implement it in the custom objects of your application, including custom views.
[Apple documentation](https://developer.apple.com/library/ios/documentation/General/Conceptual/DevPedia-CocoaCore/KVO.html)

`UITabBarItem` is one of these "general classes".

**Comment by jlnr** [comment]
Time for UIView.jlnr_barItem? ;)

Sent from my iPhone

**Comment by sebastianludwig** [comment]
Never mind...seems to work. I was using the wrong `tabBarItem` in `StylingViewController`. And I found out while using `JLNRTabBarItem` ;-)
